version: '2'
services:
  api:
    build: Docker/PHP7
    restart: never
    command: bash -c "chmod +x /home/run.sh; /home/run.sh"
    volumes:
      - ./Docker/PHP7/run.sh:/home/run.sh
      - ./web:/var/www/html
      - ./Logs/PHP7:/tmp/logs

    ports:
      - "80:80"
    links:
      - mysql
      - memcache

  mysql:
    image: mysql:5.7
    restart: never
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hostapi
      - MYSQL_DATABASE=example
    volumes:
      - ./Docker/Mysql/data:/var/lib/mysql

  memcache:
    build: Docker/Memcache
    ports:
      - "11211:11211"
