version: '2'
services:
  apiphp5:
    build: Docker/PHP5
    restart: never
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    links:
      - mysql
      - memcache

  mysql:
    image: mysql:5.7
    restart: never
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hostapi
      - MYSQL_DATABASE=example
    volumes:
      - ./Docker/Mysql/data:/var/lib/mysql

  memcache:
    build: Docker/Memcache
    ports:
      - "11211:11211"
